services:
#    default.example:
#        class: DefaultBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]



    current_date:
        class: DefaultBundle\Services\CurrentDate
        